name: supabase_authentication_client
description: A Supabase implementation of the authentication client interface
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  sign_in_with_apple: ^6.1.0
  supabase_flutter: ^2.0.0
  token_storage:
    path: ../token_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^6.0.0
