name: appwrite_authentication_client
description: An Appwrite implementation of the authentication client interface
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  appwrite: ^17.0.0
  authentication_client:
    path: ../authentication_client
  flutter:
    sdk: flutter
  token_storage:
    path: ../token_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^6.0.0
